- alias: Reset SousSol_Atelier state
  hide_entity: true
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.SousSol_Atelier
      from: 'off'
      to: 'on'
      for:
        seconds: 5
  action:
    - service: mqtt.publish
      data:
        topic: tele/sonoff/RESULT
        payload: E6DD5Eoff
