- alias: 'Update Bin Night'
  trigger:
    - event: start
      platform: homeassistant
    - platform: time_pattern
      hours: '/1'
      minutes: 0
      seconds: 0
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.recycling_bin_today, sensor.recycling_bin_tomorrow, sensor.green_bin_today, sensor.green_bin_tomorrow
- alias: 'Bin Night'
  initial_state: 'on'
  trigger:
    - platform: time
      at: '19:00:00'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ now().strftime("%H:%M") == "19:00" and now().weekday() == 1 }}'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.recycling_bin_today
            state: 'True'
          - condition: state
            entity_id: sensor.green_bin_today
            state: 'True'
  action:
    - service: notify.notify
      data_template:
        message: '{%- if (states.sensor.recycling_bin_today.state) == "True" -%} Recycling Bin Night {%- else -%} Green Bin Tonight {%- endif -%}'
        title: Bins Out Tonight